CONNECT system/pass@XEPDB1;
CREATE TABLESPACE ALQTSDEF DATAFILE '/opt/oracle/oradata/XE/ALQTSDEF.dbf'  size 2m autoextend on;
CREATE TEMPORARY TABLESPACE ALQTSTEMP TEMPFILE '/opt/oracle/oradata/XE/ALQTSTEMP.dbf' size 2m autoextend on;
CREATE USER ALQUILER IDENTIFIED BY pass DEFAULT TABLESPACE ALQTSDEF TEMPORARY TABLESPACE ALQTSTEMP QUOTA 2M ON ALQTSDEF;
SELECT USERNAME,PASSWORD,DEFAULT_TABLESPACE,TEMPORARY_TABLESPACE FROM SYS.DBA_USERS WHERE USERNAME = 'ALQUILER';
GRANT CONNECT,RESOURCE TO ALQUILER;
GRANT CREATE VIEW TO ALQUILER;
CREATE TEMPORARY TABLESPACE ALQTSTEMP TEMPFILE '/opt/oracle/oradata/XE/ALQTSTEMP.dbf' size 2m autoextend on;
CREATE USER PEPITO IDENTIFIED BY pass