/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 	*/
/*  DBMS       : Oracle                                 */
/*  Autor : Alba Consuelo Nieto Lemus			*/			
/* ---------------------------------------------------- */

/* Drop Tables */

connect ALQUILER/pass@XEPDB1;

begin
	EXECUTE IMMEDIATE 'DROP TABLE   Agencia CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   Cliente CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   Detalle_Mantenimiento CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   Mantenimiento CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   Reserva CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   Servicio CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   Taller CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   Taller_Servicio CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   Tarifa CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   Vehiculo CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   Vehiculo_Reserva CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;
/

/* Create Tables */

CREATE TABLE  Agencia
(
	K_AGENCIA VARCHAR(6) NOT NULL,	-- Nemonico de la agencia
	N_NOMBRE VARCHAR(25) NOT NULL	-- Nombre de la agencia
)
;

CREATE TABLE  Cliente
(
	K_CODCLIENTE NUMBER(5) NOT NULL,	-- Codigo interno del cliente
	N_NOMBRE1 VARCHAR(15) NOT NULL,	-- Primer nombre
	N_NOMBRE2 VARCHAR(15) NULL,	-- Segundo nombre
	N_APELLIDO1 VARCHAR(15) NOT NULL,	-- Primer apellido
	N_APELLIDO2 VARCHAR(15) NULL,	-- Segundo apellido
	N_DIRECCION VARCHAR(50) NOT NULL,	-- Direccion del cliente
	Q_TELEFONO NUMBER(10) NOT NULL,	-- Telefono de contacto del cliente
	K_CODREF NUMBER(5) NULL,	-- Codigo del cliente que referencia al cliente
	I_TIPOID VARCHAR(2) NOT NULL,	-- Tipo de identificacion (CC,CE,PA,NI,OT)
	Q_IDENTIFICACION VARCHAR(10) NOT NULL	-- Numero de identificacion del cliente
)
;

CREATE TABLE  Detalle_Mantenimiento
(
	K_PLACA VARCHAR(6) NOT NULL,	-- Placa del vehiculo
	K_MANTENIMIENTO NUMBER(3) NOT NULL,	-- Codigo del servicio de mantenimiento prestado al vehiculo
	K_TALLER NUMBER(3) NOT NULL,	-- Taller al que ingreso el vehiculo
	K_SERVICIO VARCHAR(5) NOT NULL	-- Servicio de mantenimiento  prestado en el taller
)
;

CREATE TABLE  Mantenimiento
(
	K_MANTENIMIENTO NUMBER(3) NOT NULL,	-- Codigo de mantenimiento. Es un consecutivo que inicia en 1  y se va incrementando a medida que se registra un mantenimeinto para cada vehiculo
	F_INIMTO DATE NOT NULL,	-- Fecha en que ingresa el vehiculo al taller de mantenimiento
	F_FINMTO DATE NULL,	-- Fecha en que sale el vehiculo del taller de mantenimiento
	V_TOTAL NUMBER(10,2) NULL,	-- Valor total del mantenimiento realizado a un vehiculo
	N_OBSERVACION VARCHAR(200) NOT NULL,	-- Notas del servicio de mantenimiento realizado al vehiculo
	K_PLACA VARCHAR(6) NOT NULL	--  	Placa a del vehiculo al que se le hizo el manteniemiento 
)
;

CREATE TABLE  Reserva
(
	K_RESERVA NUMBER(7) NOT NULL,	-- Consecutivo de cada reserva
	F_RESERVA DATE NOT NULL,	-- Fecha en que se realiza la reserva
	F_INICIAL DATE NOT NULL,	-- Fecha inicial de la reserva
	F_FINAL DATE NOT NULL,	-- Fecha final de la reserva
	V_TOTAL NUMBER(10,2) NOT NULL,	-- Valor total de la reserva
	I_ESTADO VARCHAR(3) NOT NULL,	-- Estado de la reserva
	K_AGENCIA VARCHAR(6) NOT NULL,--*TO DO DONE *  Adicione el código de la agencia asociada a la reserva  
	K_CODCLIENTE NUMBER(5) NOT NULL
)
;

CREATE TABLE  Servicio
(
	K_SERVICIO VARCHAR(5) NOT NULL,	-- Codigo del servicio. Es el nombre corto del servicio
	N_NOMSERV VARCHAR(15) NOT NULL	-- Nombre largo del servicio
)
;

CREATE TABLE  Taller
(
	K_TALLER NUMBER(3) NOT NULL,	-- Codigo del taller. Se asigna consecuticamente a medida que se registran los talleres
	N_TALLER VARCHAR(50) NOT NULL,	-- Nombre del taller de mantenimiento
	N_DIRECCION VARCHAR(50) NOT NULL,	-- Direccion del taller
	Q_TELEFONO NUMBER(10) NOT NULL,	-- Telefono de contacto del taller
	N_ESPECIALIDAD VARCHAR(20) NOT NULL	-- Nombre de la especialidad del taller (MECANICA, ELECTRICIDAD, LATONERIA Y PINTURA, FRENOS)
)
;

CREATE TABLE  Taller_Servicio
(
	K_TALLER NUMBER(3) NOT NULL,	-- Codigo del taller
	K_SERVICIO VARCHAR(5) NOT NULL,	-- Codigo del del servicio prestado por el taller
	V_SERVICIO NUMBER(10,2) NOT NULL	-- Precio del servicio de para cada taller
)
;

CREATE TABLE  Tarifa
(
	K_TARIFA NUMBER(5) NOT NULL,	-- Código de la tarifa
	Q_MODELO NUMBER(4) NOT NULL,	-- Anio del modelo del vehiculo
	N_MARCA VARCHAR(20) NOT NULL,	-- Marca del vehiculo
	N_LINEA VARCHAR(20) NOT NULL,	-- Nombre de la linea del vehiculo
	V_TARIFADIARIA NUMBER(6) NOT NULL
)
;

CREATE TABLE  Vehiculo
(
	K_PLACA VARCHAR(6) NOT NULL,	-- Numero de la placa del vehiculo
	N_COLOR VARCHAR(10) NOT NULL,	-- Color del vehiculo
	I_EN_MANTO VARCHAR(1) NOT NULL,	-- Indica si el vehiculo esta o no en mantenimiento (S/N)
	K_TARIFA NUMBER(5) NULL
)
;

CREATE TABLE  Vehiculo_Reserva
(
	K_PLACA VARCHAR(6) NOT NULL,	-- Placa del vehículo
	K_RESERVA NUMBER(7) NOT NULL,	-- Codigo de la reserva
	F_ENTREGA DATE NULL,	-- Fecha en que se le entrega el vehiculo al cliente
	F_DEVOLUCION DATE NULL,	-- Fecha en que el cliente retorna el vehiculo a la agencia
	Q_GALONES NUMBER(3,1) NULL,	-- Cantidad de galones de gasolina con que el cliente devuelve el vehiculo
	N_OBSERVACION VARCHAR(50) NULL,	-- Descripcion del estado en que el cliente devuelve el vehiculo
	V_ALQUILER NUMBER(7) NOT NULL	-- Valor del alquiler del vehículo para la reserva
)
;

/* Create Comments, Sequences and Triggers for Autonumber Columns */

COMMENT ON TABLE  Agencia IS 'Cada una de las agencias en las cuales se hacen reservas'
;


COMMENT ON COLUMN  Agencia.K_AGENCIA IS 'Nemonico de la agencia';

COMMENT ON COLUMN  Agencia.N_NOMBRE IS 'Nombre de la agencia';

COMMENT ON TABLE  Cliente IS 'Datos personales de las personas que hacen reservas'
;


COMMENT ON COLUMN  Cliente.K_CODCLIENTE IS 'Codigo interno del cliente';

COMMENT ON COLUMN  Cliente.N_NOMBRE1 IS 'Primer nombre';

COMMENT ON COLUMN  Cliente.N_NOMBRE2 IS 'Segundo nombre';

COMMENT ON COLUMN  Cliente.N_APELLIDO1 IS 'Primer apellido';

COMMENT ON COLUMN  Cliente.N_APELLIDO2 IS 'Segundo apellido';

COMMENT ON COLUMN  Cliente.N_DIRECCION IS 'Direccion del cliente';

COMMENT ON COLUMN  Cliente.Q_TELEFONO IS 'Telefono de contacto del cliente';

COMMENT ON COLUMN  Cliente.K_CODREF IS 'Codigo del cliente que referencia al cliente';

COMMENT ON COLUMN  Cliente.I_TIPOID IS 'Tipo de identificacion (CC,CE,PA,NI,OT)';

COMMENT ON COLUMN  Cliente.Q_IDENTIFICACION IS 'Numero de identificacion del cliente';

COMMENT ON TABLE  Detalle_Mantenimiento IS 'Detalle de cada uno de los servicios de mantenimiento prestados a un vehiculo'
;


COMMENT ON COLUMN  Detalle_Mantenimiento.K_PLACA IS 'Placa del vehiculo';

COMMENT ON COLUMN  Detalle_Mantenimiento.K_MANTENIMIENTO IS 'Codigo del servicio de mantenimiento prestado al vehiculo';

COMMENT ON COLUMN  Detalle_Mantenimiento.K_TALLER IS 'Taller al que ingreso el vehiculo';

COMMENT ON COLUMN  Detalle_Mantenimiento.K_SERVICIO IS 'Servicio de mantenimiento  prestado en el taller';

COMMENT ON TABLE  Mantenimiento IS 'Registro historico de todos los servicios de mantenimiento que se le han realizado a un vehiculo'
;


COMMENT ON COLUMN  Mantenimiento.K_MANTENIMIENTO IS 'Codigo de mantenimiento. Es un consecutivo que inicia en 1  y se va incrementando a medida que se registra un mantenimeinto para cada vehiculo';

COMMENT ON COLUMN  Mantenimiento.F_INIMTO IS 'Fecha en que ingresa el vehiculo al taller de mantenimiento';

COMMENT ON COLUMN  Mantenimiento.F_FINMTO IS 'Fecha en que sale el vehiculo del taller de mantenimiento';

COMMENT ON COLUMN  Mantenimiento.V_TOTAL IS 'Valor total del mantenimiento realizado a un vehiculo';

COMMENT ON COLUMN  Mantenimiento.N_OBSERVACION IS 'Notas del servicio de mantenimiento realizado al vehiculo';

COMMENT ON COLUMN  Mantenimiento.K_PLACA IS 'Placa del vehiculo al que se le hizo mantenimiento ';

COMMENT ON TABLE  Reserva IS 'Informacion de las reservas realizadas en cada agencia'
;


COMMENT ON COLUMN  Reserva.K_RESERVA IS 'Consecutivo de cada reserva';

COMMENT ON COLUMN  Reserva.F_RESERVA IS 'Fecha en que se realiza la reserva';

COMMENT ON COLUMN  Reserva.F_INICIAL IS 'Fecha inicial de la reserva';

COMMENT ON COLUMN  Reserva.F_FINAL IS 'Fecha final de la reserva';

COMMENT ON COLUMN  Reserva.V_TOTAL IS 'Valor total de la reserva';

COMMENT ON COLUMN  Reserva.I_ESTADO IS 'Estado de la reserva: Pendiente, Pagada, Activa, Cancelada, Finalizada';

COMMENT ON TABLE  Servicio IS 'Servicios de mantenimiento prestados por el taller'
;


COMMENT ON COLUMN  Servicio.K_SERVICIO IS 'Codigo del servicio. Es el nombre corto del servicio';

COMMENT ON COLUMN  Servicio.N_NOMSERV IS 'Nombre largo del servicio';

COMMENT ON TABLE  Taller IS 'Talleres de mantenimiento de los vehiculos'
;


COMMENT ON COLUMN  Taller.K_TALLER IS 'Codigo del taller. Se asigna consecuticamente a medida que se registran los talleres';

COMMENT ON COLUMN  Taller.N_TALLER IS 'Nombre del taller de mantenimiento';

COMMENT ON COLUMN  Taller.N_DIRECCION IS 'Direccion del taller';

COMMENT ON COLUMN  Taller.Q_TELEFONO IS 'Telefono de contacto del taller';

COMMENT ON COLUMN  Taller.N_ESPECIALIDAD IS 'Nombre de la especialidad del taller (MECANICA, ELECTRICIDAD, LATONERIA Y PINTURA, FRENOS)';

COMMENT ON TABLE  Taller_Servicio IS 'Servicios prestados   por taller'
;


COMMENT ON COLUMN  Taller_Servicio.K_TALLER IS 'Codigo del taller';

COMMENT ON COLUMN  Taller_Servicio.K_SERVICIO IS 'Codigo del del servicio prestado por el taller';

COMMENT ON COLUMN  Taller_Servicio.V_SERVICIO IS 'Precio del servicio de para cada taller';

COMMENT ON TABLE  Tarifa IS 'Almacena las tarifas de alquiler diario dependiendo de las caracteristicas del vehiculo'
;


COMMENT ON COLUMN  Tarifa.K_TARIFA IS 'Código de la tarifa';

COMMENT ON COLUMN  Tarifa.Q_MODELO IS 'Anio del modelo del vehiculo';

COMMENT ON COLUMN  Tarifa.N_MARCA IS 'Marca del vehiculo';

COMMENT ON COLUMN  Tarifa.N_LINEA IS 'Nombre de la linea del vehiculo';

COMMENT ON TABLE  Vehiculo IS 'Vehiculos de la empresa que pueden ser alquilados'
;


COMMENT ON COLUMN  Vehiculo.K_PLACA IS 'Numero de la placa del vehiculo';

COMMENT ON COLUMN  Vehiculo.N_COLOR IS 'Color del vehiculo';

COMMENT ON COLUMN  Vehiculo.I_EN_MANTO IS 'Indica si el vehiculo esta o no en mantenimiento (S/N)';

COMMENT ON TABLE  Vehiculo_Reserva IS 'Detalle de los vehiculos  que hacen parte de una reserva'
;


COMMENT ON COLUMN  Vehiculo_Reserva.K_PLACA IS 'Placa del vehículo';

COMMENT ON COLUMN  Vehiculo_Reserva.K_RESERVA IS 'Codigo de la reserva';

COMMENT ON COLUMN  Vehiculo_Reserva.F_ENTREGA IS 'Fecha en que se le entrega el vehiculo al cliente';

COMMENT ON COLUMN  Vehiculo_Reserva.F_DEVOLUCION IS 'Fecha en que el cliente retorna el vehiculo a la agencia';

COMMENT ON COLUMN  Vehiculo_Reserva.Q_GALONES IS 'Cantidad de galones de gasolina con que el cliente devuelve el vehiculo';

COMMENT ON COLUMN  Vehiculo_Reserva.N_OBSERVACION IS 'Descripcion del estado en que el cliente devuelve el vehiculo';

COMMENT ON COLUMN  Vehiculo_Reserva.V_ALQUILER IS 'Valor del alquiler del vehículo para la reserva';

/* Create Primary Keys, Indexes, Uniques, Checks, Triggers */

ALTER TABLE  Agencia 
 ADD CONSTRAINT PK_Agencia
	PRIMARY KEY (K_AGENCIA) 
 USING INDEX
;

ALTER TABLE  Cliente 
 ADD CONSTRAINT PK_Cliente
	PRIMARY KEY (K_CODCLIENTE) 
 USING INDEX
;

ALTER TABLE  Cliente
 ADD CONSTRAINT UK_Cliente
	UNIQUE(I_TIPOID, Q_IDENTIFICACION)
 USING INDEX --*TO DO DONE *  adicione un constraint de llave única con el tipo y número de identificación del cliente
;

ALTER TABLE  Cliente 
 ADD CONSTRAINT CK_CODCLIENTE CHECK (k_codcliente >= 100)
;

ALTER TABLE  Cliente 
 ADD CONSTRAINT CK_I_TIPOID CHECK (I_TIPOID IN ('CC', 'PA', 'CE', 'NI', 'OT'))
; --*TO DO DONE * Altere la tabla Cliente para adicionar el constraint que verifique que el tipo de identificación sea CC, PA, CE, NI, OT

ALTER TABLE  Detalle_Mantenimiento 
 ADD CONSTRAINT PK_DETALLE_MTO
	PRIMARY KEY (K_PLACA, K_MANTENIMIENTO, K_TALLER, K_SERVICIO)
--*TO DO DONE * adicione la llave primaria. Tip: esta es una tabla de rompimiento
;

ALTER TABLE  Mantenimiento 
 ADD CONSTRAINT PK_MANTENIMIENT
	PRIMARY KEY (K_MANTENIMIENTO,K_PLACA) 
;

ALTER TABLE  Mantenimiento 
 ADD CONSTRAINT CK_VTOTAL_MTO CHECK (v_total > 0)
;

ALTER TABLE  Mantenimiento
 ADD CONSTRAINT CK_FINMTO
  CHECK (F_FINMTO >= F_INIMTO)
--*TO DO DONE * adicione el constraint para asegurar que la fecha de fin de mantenimiento sea mayor o igual que la fecha inicial de mantenimiento
;

ALTER TABLE  Reserva 
 ADD CONSTRAINT PK_Reserva
	PRIMARY KEY (K_RESERVA) 
 USING INDEX
;

ALTER TABLE  Reserva 
 ADD CONSTRAINT CK_VTOTAL CHECK (v_total >0)
;

ALTER TABLE  Reserva 
 ADD CONSTRAINT CK_VTOTAL CHECK (F_FINAL >= F_INICIAL >= F_RESERVA)
;--*TO DO DONE * Altere la tabla reserva para hacer que se cumpla esta regla: f_final >= f_inicial >= f_reserva

ALTER TABLE  Reserva 
 ADD CONSTRAINT CK_ESTADO CHECK (i_estado IN ('PEN', 'PAG','ACT', 'CAN','FIN'))
;

ALTER TABLE  Servicio 
 ADD CONSTRAINT PK_Servicio
	PRIMARY KEY (K_SERVICIO) 
 USING INDEX
;

ALTER TABLE  Taller 
 ADD CONSTRAINT PK_Taller
	PRIMARY KEY (K_TALLER) 
 USING INDEX
;

ALTER TABLE  Taller 
 ADD CONSTRAINT CK_ESPECIALIDAD CHECK (n_especialidad IN ('MECANICA', 'ELECTRICIDAD', 'LATONERIA Y PINTURA', 'FRENOS')
)
;

ALTER TABLE  Taller_Servicio 
 ADD CONSTRAINT PK_Taller_Servicio
	PRIMARY KEY (K_TALLER,K_SERVICIO) 
 USING INDEX
;

ALTER TABLE  Taller_Servicio 
 ADD CONSTRAINT CK_VSERVICIO CHECK (v_servicio > 0)
;

ALTER TABLE  Tarifa 
 ADD CONSTRAINT PK_Tarifa
	PRIMARY KEY (K_TARIFA) 
 USING INDEX
;

ALTER TABLE  Tarifa 
 ADD CONSTRAINT CK_TARIFADIARIA CHECK (v_tarifaDiaria > 0)
;

ALTER TABLE  Tarifa 
 ADD CONSTRAINT CK_MODELO CHECK (q_modelo > 2010)
;

ALTER TABLE  Vehiculo 
 ADD CONSTRAINT PK_Vehiculo
	PRIMARY KEY (K_PLACA) 
 USING INDEX
;

CREATE INDEX IXFK_Vehiculo_Tarifa   
 ON  Vehiculo (K_TARIFA) 
;

ALTER TABLE  Vehiculo_Reserva 
 ADD CONSTRAINT PK_VEHICULO_RESERVA
	PRIMARY KEY (K_PLACA,K_RESERVA) 
 USING INDEX
;

ALTER TABLE  Vehiculo_Reserva 
 ADD CONSTRAINT CK_GALONES CHECK (q_galones >= 0)
;

ALTER TABLE  Vehiculo_Reserva 
 ADD CONSTRAINT CK_VALQUILER CHECK (v_alquiler >0)
;

/* Create Foreign Key Constraints */

ALTER TABLE  Cliente 
 ADD CONSTRAINT FK_Cliente_Cliente
	FOREIGN KEY (K_CODREF) REFERENCES  Cliente (K_CODCLIENTE)
;

ALTER TABLE  Detalle_Mantenimiento 
 ADD CONSTRAINT FK_DetalleMto_Mantenimiento
	FOREIGN KEY(K_PLACA, K_MANTENIMIENTO) REFERENCES Mantenimiento(K_PLACA, K_MANTENIMIENTO)
	--*TO DO DONE* Adicione la llave foránea con la tabla Mantenimiento
;

ALTER TABLE  Detalle_Mantenimiento 
 ADD CONSTRAINT FK_DetalleMto_Taller_Servicio
	FOREIGN KEY (K_TALLER,K_SERVICIO) REFERENCES  Taller_Servicio (K_TALLER,K_SERVICIO)
;

ALTER TABLE  Mantenimiento 
 ADD CONSTRAINT FK_Mantenimiento_Vehiculo
	FOREIGN KEY (K_PLACA) REFERENCES  Vehiculo (K_PLACA)
;

ALTER TABLE  Reserva 
 ADD CONSTRAINT FK_Reserva_Agencia
	FOREIGN KEY (K_AGENCIA) REFERENCES  Agencia (K_AGENCIA)
;

ALTER TABLE  Reserva 
 ADD CONSTRAINT FK_Reserva_Cliente
	FOREIGN KEY (K_CODCLIENTE) REFERENCES  Cliente (K_CODCLIENTE)
;

ALTER TABLE  Taller_Servicio 
 ADD CONSTRAINT FK_Taller_Servicio_Servicio
	FOREIGN KEY (K_SERVICIO) REFERENCES  Servicio (K_SERVICIO)
;

ALTER TABLE  Taller_Servicio 
 ADD CONSTRAINT FK_Taller_Servicio_Taller
	FOREIGN KEY (K_TALLER) REFERENCES  Taller (K_TALLER)
;

ALTER TABLE  Vehiculo 
 ADD CONSTRAINT FK_Vehiculo_Tarifa
	FOREIGN KEY (K_TARIFA) REFERENCES  Tarifa (K_TARIFA)
;

ALTER TABLE  Vehiculo_Reserva 
 ADD CONSTRAINT FK_VEHICULO_RESERVA_RESERVA
	FOREIGN KEY (K_RESERVA) REFERENCES  Reserva (K_RESERVA)
;

ALTER TABLE  Vehiculo_Reserva 
 ADD CONSTRAINT FK_VEHICULO_RESERVA_VEHICULO
	FOREIGN KEY (K_PLACA) REFERENCES  Vehiculo (K_PLACA)
;
