--------------------------------------------------------
-- Archivo creado  - ago 2023
--------------------------------------------------------
connect ALQUILER/pass@XEPDB1;
REM INSERTING into TARIFA
SET DEFINE OFF;
Insert into TARIFA (K_TARIFA,Q_MODELO,N_MARCA,N_LINEA,V_TARIFADIARIA) values ('1','2011','RENAULT','SANDERO','110000');
Insert into TARIFA (K_TARIFA,Q_MODELO,N_MARCA,N_LINEA,V_TARIFADIARIA) values ('2','2012','RENAULT','SANDERO','120000');
Insert into TARIFA (K_TARIFA,Q_MODELO,N_MARCA,N_LINEA,V_TARIFADIARIA) values ('3','2013','CHEVROLET','CORSA','130000');
Insert into TARIFA (K_TARIFA,Q_MODELO,N_MARCA,N_LINEA,V_TARIFADIARIA) values ('4','2014','CHEVROLET','SWIFT','135000');
Insert into TARIFA (K_TARIFA,Q_MODELO,N_MARCA,N_LINEA,V_TARIFADIARIA) values ('5','2015','MAZDA','MAZDA 3','150000');
Insert into TARIFA (K_TARIFA,Q_MODELO,N_MARCA,N_LINEA,V_TARIFADIARIA) values ('6','2018','KIA','PICANTO','160000');
Insert into TARIFA (K_TARIFA,Q_MODELO,N_MARCA,N_LINEA,V_TARIFADIARIA) values ('7','2018','HYUNDAI','ACCENT','180000');
Insert into TARIFA (K_TARIFA,Q_MODELO,N_MARCA,N_LINEA,V_TARIFADIARIA) values ('8','2018','VOLSKWAGEN','GOLF','200000');
