--------------------------------------------------------
-- Archivo creado  - ago 2023
--------------------------------------------------------
connect ALQUILER/pass@XEPDB1;
REM INSERTING into VEHICULO_RESERVA
SET DEFINE OFF;
Insert into VEHICULO_RESERVA (K_PLACA,K_RESERVA,F_ENTREGA,F_DEVOLUCION,Q_GALONES,N_OBSERVACION,V_ALQUILER) values ('MCT111','20231',null,null,null,null,'330000');
Insert into VEHICULO_RESERVA (K_PLACA,K_RESERVA,F_ENTREGA,F_DEVOLUCION,Q_GALONES,N_OBSERVACION,V_ALQUILER) values ('ABC222','20231',null,null,null,null,'360000');
Insert into VEHICULO_RESERVA (K_PLACA,K_RESERVA,F_ENTREGA,F_DEVOLUCION,Q_GALONES,N_OBSERVACION,V_ALQUILER) values ('WER333','20232',null,null,null,null,'260000');
Insert into VEHICULO_RESERVA (K_PLACA,K_RESERVA,F_ENTREGA,F_DEVOLUCION,Q_GALONES,N_OBSERVACION,V_ALQUILER) values ('WER333','20234',null,null,null,null,'520000');
Insert into VEHICULO_RESERVA (K_PLACA,K_RESERVA,F_ENTREGA,F_DEVOLUCION,Q_GALONES,N_OBSERVACION,V_ALQUILER) values ('JKU666','20233',to_date('19/08/23','DD/MM/RR'),null,null,null,'800000');
Insert into VEHICULO_RESERVA (K_PLACA,K_RESERVA,F_ENTREGA,F_DEVOLUCION,Q_GALONES,N_OBSERVACION,V_ALQUILER) values ('CET888','20235',to_date('19/08/23','DD/MM/RR'),null,null,null,'2400000');
Insert into VEHICULO_RESERVA (K_PLACA,K_RESERVA,F_ENTREGA,F_DEVOLUCION,Q_GALONES,N_OBSERVACION,V_ALQUILER) values ('GHT777','20235',null,null,null,null,'2160000');
Insert into VEHICULO_RESERVA (K_PLACA,K_RESERVA,F_ENTREGA,F_DEVOLUCION,Q_GALONES,N_OBSERVACION,V_ALQUILER) values ('GHT777','20236',null,null,null,null,'2160000');
Insert into VEHICULO_RESERVA (K_PLACA,K_RESERVA,F_ENTREGA,F_DEVOLUCION,Q_GALONES,N_OBSERVACION,V_ALQUILER) values ('CET888','20236',null,null,null,null,'2160000');
